### ISSUE TITLE
BTC wallet shows 0.00 BTC if small amount of BTC is held

### ISSUE THREAD

**Issue by danlipert** [HoardInvest/hoard#305]
If you hold less than 0.01 BTC, it shows as 0.00 in the card in the Bitcoin wallet.

**Comment by zachgibb** [comment]
@danlipert would just showing the full balance be feasible to solve this? On a small screen, we can fit up to 29 decimals in the header before it breaks onto a new line. Since most coins don't subdivide past 8 or 9 decimals, you would need to hold quintillions of a coin before the header breaks.... which seems unlikely to happen. 

<img width="306" alt="image" src="https://user-images.githubusercontent.com/8093376/51154145-df9b9600-1840-11e9-86b4-80d8d05b85c4.png">

**Comment by danlipert** [comment]
@zachgibb yeah definitely (at least for now)! There probably will be coins in the future where we will have to deal with this though.
